#!/usr/bin/env python3
"""
Khoj AI Second Brain - Hermes Integration Script

Quick research using Khoj's API. Saves findings to Obsidian vault.
"""

import sys
import os
import requests
from datetime import datetime

# Configuration
KHOJ_API_URL = os.environ.get("KHOJ_API_URL", "https://app.khoj.dev/api")
KHOJ_API_KEY = os.environ.get("KHOJ_API_KEY", "")
OBSIDIAN_VAULT = os.path.expanduser("~/Obsidian-Vault")

def khoj_chat(query, stream=False):
    """Send chat message to Khoj API."""
    headers = {"Content-Type": "application/json"}
    if KHOJ_API_KEY:
        headers["Authorization"] = f"Bearer {KHOJ_API_KEY}"
    
    try:
        response = requests.post(
            f"{KHOJ_API_URL}/chat",
            json={"q": query, "stream": stream},
            headers=headers,
            timeout=30
        )
        return response.json()
    except Exception as e:
        return {"error": str(e)}

def khoj_search(query, limit=5):
    """Semantic search in Khoj knowledge base."""
    headers = {}
    if KHOJ_API_KEY:
        headers["Authorization"] = f"Bearer {KHOJ_API_KEY}"
    
    try:
        response = requests.get(
            f"{KHOJ_API_URL}/search?q={query}&limit={limit}",
            headers=headers,
            timeout=30
        )
        return response.json()
    except Exception as e:
        return {"error": str(e)}

def save_research(query, response, save_path=None):
    """Save research results to Obsidian vault."""
    date = datetime.now().strftime('%Y-%m-%d')
    
    if save_path is None:
        save_dir = os.path.join(OBSIDIAN_VAULT, "research", date)
        os.makedirs(save_dir, exist_ok=True)
        safe_name = query.replace(" ", "-")[:50]
        save_path = os.path.join(save_dir, f"{safe_name}.md")
    
    content = f"""# Research: {query}
Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Query
{query}

## Response
{response.get('response', response.get('text', 'No response'))}

## Sources
{response.get('sources', 'N/A')}

---
*Generated by Hermes + Khoj*
"""
    
    with open(save_path, 'w') as f:
        f.write(content)
    
    return save_path

def main():
    if len(sys.argv) < 2:
        print("Usage: khoj-research.py <query> [--save]")
        print("Example: khoj-research.py 'latest crypto trading strategies' --save")
        sys.exit(1)
    
    query = sys.argv[1]
    save = "--save" in sys.argv
    
    print(f"🔍 Researching: {query}")
    
    # Try chat first
    result = khoj_chat(query)
    
    if "error" in result:
        # Try search as fallback
        print("Trying semantic search...")
        result = khoj_search(query)
    
    if "error" not in result:
        print(f"\n📝 Response:")
        print(result.get("response", result))
        
        if save:
            path = save_research(query, result)
            print(f"\n💾 Saved to: {path}")
    else:
        print(f"❌ Error: {result.get('error')}")
        print("💡 Tip: Set KHOJ_API_KEY environment variable for authenticated requests")

if __name__ == "__main__":
    main()